import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import SideBar from "../_components/SideBar";
import NavBar from "../_components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dev Quest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
